### ISSUE TITLE
Points err

### ISSUE THREAD

**Issue by 2551654928** [wployalty/wployalty_auto_currency#17]
Calculate points after discount: Order price in USD - Multi-currency price, e.g. Points = USD - JPY.How to set points = USD-USD.

**Comment by 2551654928** [comment]
@alagesanbe08

**Comment by alagesanbe08** [comment]
NOTE: you have to install WPLoyalty Multi-currency Plugin, Right now, it support 
1. CURCY – Multi Currency for WooCommerce (Free version only)
2. WooCommerce Multilingual & Multicurrency with WPML
3. Aelia Currency Switcher for WooCommerce
4. FOX – Currency Switcher Professional for WooCommerce


Store Currency: USD
Supported Currencies: USD, JPY

In all campaigns and rewards, point conversions are conducted using the store's currency, which in this instance is USD.

For instance, consider the "point for purchase" campaign where you establish a 1-point-to-1-USD conversion rate within the store's currency. Furthermore, assume a conversion ratio of 1 USD to 2 JPY.

When your shopping cart total amounts to 50 USD, you will acquire 50 points. Similarly, when your cart totals 100 JPY, you will also earn 50 points, taking into account the conversion ratio of 1 USD to 2 JPY.

It is important to note that the "point for purchase" conversion can be configured exclusively within the Store Currency.

**Comment by alagesanbe08** [comment]
duplicate #18
