### ISSUE TITLE
don't suport CURCY - WooCommerce Multi Currency Premium

### ISSUE THREAD

**Issue by 2551654928** [wployalty/wployalty_auto_currency#18]
It not suport CURCY - WooCommerce Multi Currency Premium

**Comment by alagesanbe08** [comment]
Yes.. Right now.. it not support CURCY - WooCommerce Multi Currency Premium

We will include CURCY - WooCommerce Multi Currency Premium

**Comment by 2551654928** [comment]
Thank you so much

**Comment by 2551654928** [comment]
Excuse me, when's the approximate update?

**Comment by alagesanbe08** [comment]
Included: CURCY - WooCommerce Multi Currency Premium
