### ISSUE TITLE
Currency not converted properly

### ISSUE THREAD

**Issue by Mercypaul27** [wployalty/wployalty_auto_currency#25]
this is $1.00 after converting INR it should be shown as 0.5 INR but now showing inr 1.00
![image](https://github.com/wployalty/wployalty_auto_currency/assets/107607148/08259822-0b3c-42c6-8743-a630ec69a30a)
![image](https://github.com/wployalty/wployalty_auto_currency/assets/107607148/0202fc4b-b68a-43af-8168-c61601b1d1f5)

**Comment by mohansethupathi** [comment]
Issues Cleared

**Comment by Mercypaul27** [comment]
Fixed
![image](https://github.com/wployalty/wployalty_auto_currency/assets/107607148/94660c9e-af66-4022-a31d-1858b81fce53)
![image](https://github.com/wployalty/wployalty_auto_currency/assets/107607148/21e29717-4bc8-43cf-a7c0-53ece0fe7b2c)
![image](https://github.com/wployalty/wployalty_auto_currency/assets/107607148/be368597-b64f-4e3e-b0ea-c62c044d1892)
