### ISSUE TITLE
When Fixed Discount reward applied as coupon not applied properly

### ISSUE THREAD

**Issue by HemaR03** [wployalty/wployalty_auto_currency#39]
Reward:
![image](https://github.com/user-attachments/assets/5eff4039-e2f1-499e-b9f0-ffebccd7512a)
Campgain - Reward based on spending
![image](https://github.com/user-attachments/assets/de752066-30b5-4a75-b499-385a58657b8e)
Customer Reward page:
In INR:
![image](https://github.com/user-attachments/assets/edfff6e2-ff0c-467f-b176-6300adfb03d8)
In USD:
![image](https://github.com/user-attachments/assets/98f4f5f8-d664-4d44-9751-3d9e2043ea52)

**Comment by sabhari-krr** [comment]
Fixed. Use the updated v1.2.11 loyalty pack.

**Comment by HemaR03** [comment]
Issue Fixed
![image](https://github.com/user-attachments/assets/512311b7-6beb-484e-a0ca-dd8e45cb84d7)
![image](https://github.com/user-attachments/assets/fc8ffee7-0251-4667-b2f9-f41c867b9c71)
![image](https://github.com/user-attachments/assets/2ecec682-eedd-4a58-a3c7-c078a15b1de4)
![image](https://github.com/user-attachments/assets/54727c4e-f570-4187-930c-6c4ea56e2324)
